# Exercici NN 

In [53]:
import numpy as np
import idx2numpy

## Linear Layer
Forward y backward


In [49]:
class linear_layer():
    def __init__(self, input_dimensions, output_dimensions):
        self.W=2*np.random.rand(input_dimensions, output_dimensions)-1
        self.B=np.random.rand(1, output_dimensions)
 
    def forward(self,x):
        self.x = x
        return x @ self.W+self.B
 
    def backward(self,error):
        self.dW= self.x.T @ error 
        self.dB= error.sum(axis=0)
        return error @ self.W.T
 
    def update_parameters(self, lr):
        self.W=self.W - lr * self.dW
        self.B= self.B- lr * self.dB
        print(self.W)
 

In [75]:
nn1 = linear_layer(5,2)
print("W",nn1.W)
x = np.array([[1,0,1,1,0],[1,1,0,1,0]])

yp = nn1.forward(x)
error = np.array([[ 0.53244288 , 1.77576889],[ 0.26388718, -1.35265955]])

nn1.backward(error)
print(nn1.W)
print("dW:",nn1.dW)

nn1.update_parameters(0.03)
print(nn1.W)

[[ 0.78916236 -0.80319467]
 [ 0.22981648 -0.526451  ]
 [ 0.78627956  0.78387721]
 [ 0.05834171 -0.96888867]
 [-0.86895986 -0.27437366]]
W [[ 0.78916236 -0.80319467]
 [ 0.22981648 -0.526451  ]
 [ 0.78627956  0.78387721]
 [ 0.05834171 -0.96888867]
 [-0.86895986 -0.27437366]]
[[ 0.78916236 -0.80319467]
 [ 0.22981648 -0.526451  ]
 [ 0.78627956  0.78387721]
 [ 0.05834171 -0.96888867]
 [-0.86895986 -0.27437366]]
dW: [[ 0.79633006  0.42310934]
 [ 0.26388718 -1.35265955]
 [ 0.53244288  1.77576889]
 [ 0.79633006  0.42310934]
 [ 0.          0.        ]]
[[ 0.76527246 -0.81588795]
 [ 0.22189987 -0.48587121]
 [ 0.77030627  0.73060415]
 [ 0.03445181 -0.98158195]
 [-0.86895986 -0.27437366]]
[[ 0.76527246 -0.81588795]
 [ 0.22189987 -0.48587121]
 [ 0.77030627  0.73060415]
 [ 0.03445181 -0.98158195]
 [-0.86895986 -0.27437366]]


In [43]:
class Relu_layer():
    def __init__(self):
        pass
 
    def forward(self,x):
        self.Z=np.maximum(0,x)
        return self.Z
 
    def backward(self,error):
        return error * (self.Z > 0)
 
    def update_parameters(self, lr):
        return True

# Input


In [44]:
class input_layer():
    def __init__(self, input_size):
        self.input_size = input_size
 
 
    def forward(self,x):
        return x
 
    def backward(self,error):
        return error
 
    def update_parameters(self, lr):
        return True

## Model design

In [46]:
class NN_model():
    def __init__(self):
        self.sequential = [input_layer(4),
                            linear_layer(4,4),
                            Relu_layer(),
                            linear_layer(4,4),
                            Relu_layer(),
                            linear_layer(4,3)]

    def forward(self, x):
        for layer in self.sequential:
            y = layer.forward(x)
            x = y
        return y

    def backward(self, error):
        for layer in np.flip(self.sequential):
            y = layer.backward(error)
            error = y
        return error 

    def update_parameters(self, learning_rate=0.03):
        for layer in self.sequential:
            layer.update_parameters(learning_rate)

model = NN_model()
x = np.array([[1,-10,1,-8],[2,2,0,0]])

y_pred = model.forward(x)

y_real = np.array([[1,-10,0],[1,0,1]])

error = 2 * (y_pred - y_real)

model.backward(error)
model.update_parameters(0.03)

[[-0.56560238 -0.82656385  0.0932422  -1.28058879]
 [ 0.16260684  2.17556036  0.38380645  0.54935592]
 [ 0.52921886  0.31668034  0.68037842  0.55816561]
 [ 0.7925816   1.57272011  0.65457367 -0.85226501]]
[[-0.71260777  0.72842742  0.11028761 -0.09821724]
 [-1.58721355 -0.30492143 -0.28759269 -0.24705305]
 [ 0.23647216  0.41030074  0.44155562 -0.57007244]
 [ 0.28942902 -0.6343368   0.86004849  0.9424777 ]]
[[-4.91085498 -2.92559166  1.64418623]
 [-5.74644723 -4.64883802  1.40370214]
 [ 0.16697943  0.28542747  0.32417383]
 [ 0.72713025 -0.68612    -0.64293531]]


## Paso a paso 

In [63]:
x = np.array([[1,0,1,1,0],[1,1,0,1,0]])
yr = np.array([[ 0.53244288 , 1.77576889],[ 0.26388718, -1.35265955]])

seq = [linear_layer(5,2),linear_layer(2,2)]

y1 = seq[0].forward(x)
y2 = seq[1].forward(y1)

error2 = 2*(y2 - yr)
error1 = seq[1].backward(error2)
error0 = seq[0].backward(error1)

seq[0].dW

seq[0].update_parameters(0.03)
seq[1].update_parameters(0.03)


y1 = seq[0].forward(x)
y2 = seq[1].forward(y1)

error2 = 2*(y2 - yr)
error1 = seq[1].backward(error2)
error0 = seq[0].backward(error1)

seq[0].update_parameters(0.03)
seq[1].update_parameters(0.03)


[[-0.93224254 -0.29471037]
 [ 0.41563523  0.73358615]
 [ 0.1403662   0.88875886]
 [ 0.12749836  0.32891316]
 [-0.5230961  -0.37105466]]
[[-0.9078399  -0.56180373]
 [-0.94310149 -0.52978563]]
[[-1.02723573 -0.39339812]
 [ 0.42413841  0.73748118]
 [ 0.03686984  0.78617607]
 [ 0.03250518  0.23022541]
 [-0.5230961  -0.37105466]]
[[-0.93423247 -0.58701846]
 [-0.82585891 -0.51566113]]
[[-1.00330103 -0.37239479]
 [ 0.48615163  0.79193694]
 [-0.00120868  0.75272365]
 [ 0.05643988  0.25122875]
 [-0.5230961  -0.37105466]]
[[-0.93602621 -0.59387583]
 [-0.82270199 -0.54781216]]


## Leer el dataset (idx2numpy)

In [85]:
# Reading Train
X_Train = idx2numpy.convert_from_file('./Data/train-images.idx3-ubyte')
y_Train = idx2numpy.convert_from_file('./Data/train-labels.idx1-ubyte')


# Reading Real
X_Test = idx2numpy.convert_from_file('./Data/t10k-images.idx3-ubyte')
y_Test = idx2numpy.convert_from_file('./Data/t10k-labels.idx1-ubyte')


## Dataloader

In [91]:
class Dataloader():
    def __init__(self,X,y, batch_size,shuffle = True):
        self.bs = batch_size

        randomizer = np.arange(len(y)) # np.arange = np.array(range(len(y)))
        if shuffle:
            np.random.shuffle(randomizer)

        self.X = X[randomizer]
        self.y = y[randomizer]
    
    def __len__(self):
        return len(self.y)

    def __getitem__(self,idx):
        return self.X[idx]/255,self.y[idx]
    
    





## One Hot Encoding

In [97]:
test_dt = Dataloader(X_Train,y_Train,100)
dt_x,dt_y = test_dt[5:20]
print(dt_y)

def foo(y,num_classes):
    y_one_hot_encoded = np.zeros((len(y), num_classes)) #len(y) == y.shape[0]
    y_one_hot_encoded[np.arange(len(y)),y] = 1
    print(y_one_hot_encoded)
    return y_one_hot_encoded

[0 0 2 3 2 3 8 1 5 4 0 5 9 0 7]


## Steps & Train Loop

In [100]:
def train_step(model, X, y,lr, verbose = True):
    # La X és un batch de dades
    logits = model.forward(X) #ypred
    yreal = foo(y)
    error = 2 * (logits - yreal)
    model.backward(error)
    model.update_parameters(learning_rate=lr)
    cost = (logits - yreal) ** 2

    if verbose == True:
         print(f'Funció de cost: {cost}')

def train_loop(model, dataloader, learning_rate):
        
        for i in np.arange(0, len(dataloader), dataloader.bs):
            X_batch, y_batch = dataloader[i:i+dataloader.bs]
            ypred = model.forward(x_batch)
            error = y_pred - y_batch
            model.backward(error)
            model.update_parameters()

In [ ]:
def main():